import 'package:freezed_annotation/freezed_annotation.dart';

part 'student_entity.freezed.dart';

@freezed
abstract class StudentEntity with _$StudentEntity {
  const factory StudentEntity({
    required String noKodeSekolah,
    required String noKodeKecamatan,
    required String noKodeKabupatenKota,
    required String noKodeProvinsi,
    required String nis,
    String? nisn,
    String? nama,
    required String namaPanggilan,
    required String tempatLahir,
    DateTime? tanggalLahir,
    String? jenisKelamin,
    String? agama,
    required String kewarganegaraan,
    String? alamat,
    required String kodePos,
    required String bertempatTinggalPada,
    required String jarakKeSekolah,
    String? noTelepon,
    String? diTerimaDiKelas,
    String? nomorKelas,
    required DateTime tanggalDiTerima,
    String? semester,
    String? namaSekolahAsal,
    String? alamatSekolahAsal,
    String? tahunIjazah,
    String? noIjazah,
    required String tanggalIjazah,
    required String tahunSKHUN,
    required String noSKHUN,
    required String pindahanDariSekolah,
    required String dariTingkat,
    required String diTerimaTanggal,
    required String nomorSuratKeteranganPindah,
    String? anakKe,
    required String jumlahSaudaraKandung,
    required String jumlahSaudaraTiri,
    required String jumlahSaudaraAngkat,
    required String bahasaSehariHariDiRumah,
    required String golonganDarah,
    required String statusKeluarga,
    String? namaAyah,
    String? namaIbu,
    required String pendidikanTerakhirAyah,
    required String pendidikanTerakhirIbu,
    String? pekerjaanAyah,
    String? pekerjaanIbu,
    String? alamatOrangTua,
    String? noTeleponOrangTua,
    required String namaWali,
    required String alamatWali,
    required String hubunganKeluargaDenganWali,
    required String pendidikanTerakhirWali,
    required String noTeleponWali,
    required String pekerjaanWali,
    String? email,
    String? passsword,
    String? kelasSaatIni,
    String? noKelasSaatIni,
    required String tahunLulus,
    required String nomorIjazahLulus,
    required String melanjutkanKeSekolah,
    required String pindahSekolahKeSekolah,
    required String tingkatKelasYangDiTinggalkan,
    required String alasanKeluarSekolah,
    required String hariDanTanggalKeluarSekolah,
    required String tinggiBadanSemesterGanjil,
    required String beratBadanSemesterGanjil,
    required String pendengaranSemesterGanjil,
    required String penglihatanSemesterGanjil,
    required String gigiSemesterGanjil,
    required String tinggiBadanSemesterGenap,
    required String beratBadanSemesterGenap,
    required String pendengaranSemesterGenap,
    required String penglihatanSemesterGenap,
    required String gigiSemesterGenap,
    required String jenisPrestasiSainsSeniAtauOlahraga,
    required String
    tingkatPrestasiSekolahKecamatanKabupatenProvinsiAtauNasional,
    required String namaPrestasiLombaCerdasCermat,
    required String tahunPrestasiYangPernahDiraih,
    required String
    penyelenggaraNamaPenyelenggaraAtauPanitiaKegiatanDariPrestasi,
    required String peringkatAngkaPeringkatPrestasiYangPernahDiraih,
    required String jenisBeasiswaAnakBerprestasiAnakUnggulUnggulanAtauLainlain,
    required String keteranganBeasiswaMuridBerprestasiTahun2022,
    required String tahunMulaiTahunMulaiDiterimanyaBeasiswaOlehPesertaDidik,
    required String tahunSelesaiTahunSelesaiDiterimanyaBeasiswaOlehPesertaDidik,
    required String setelahSelesaiPendidikanMeninggalkanSekolah,
    required String keluarKarena,
    required String tanggalKeluar,
    required String akhirPendidikan,
    required String tamatBelajar,
    required String nomorIjazah,
    String? aktif,
    required String statusNaik,
    required String usernameOrangTua,
    required String passwordOrangTua,
    String? statusUjian,
    String? profileImageUrl,
    String? unit,
  }) = _StudentEntity;
}
